/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Trade, tradeSchema } from './trade';

export interface Data3 {
  trades?: Trade[];
}

export const data3Schema: Schema<Data3> = object({
  trades: ['trades', optional(array(lazy(() => tradeSchema)))],
});
