/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface Data {
  wallet?: string;
  balanceUsd?: number;
  balanceHistory?: number[];
}

export const dataSchema: Schema<Data> = object({
  wallet: ['wallet', optional(string())],
  balanceUsd: ['balance_usd', optional(number())],
  balanceHistory: ['balance_history', optional(array(number()))],
});
