/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { NFTTransaction, nFTTransactionSchema } from './nFTTransaction';

export interface Data6 {
  transactions?: NFTTransaction[];
}

export const data6Schema: Schema<Data6> = object({
  transactions: [
    'transactions',
    optional(array(lazy(() => nFTTransactionSchema))),
  ],
});
