/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Asset2, asset2Schema } from './asset2';

export interface Data7 {
  assets?: Asset2[];
}

export const data7Schema: Schema<Data7> = object({
  assets: ['assets', optional(array(lazy(() => asset2Schema)))],
});
