/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, object, optional, Schema } from '../schema';
import { MarketMetrics, marketMetricsSchema } from './marketMetrics';

export interface MarketMultiDataResponse {
  data?: Record<string, MarketMetrics>;
}

export const marketMultiDataResponseSchema: Schema<MarketMultiDataResponse> = object(
  { data: ['data', optional(dict(lazy(() => marketMetricsSchema)))] }
);
