/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Data3, data3Schema } from './data3';

export interface MarketTradesResponse {
  data?: Data3;
}

export const marketTradesResponseSchema: Schema<MarketTradesResponse> = object({
  data: ['data', optional(lazy(() => data3Schema))],
});
