/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Data8, data8Schema } from './data8';

export interface QuoteResponse {
  data?: Data8;
}

export const quoteResponseSchema: Schema<QuoteResponse> = object({
  data: ['data', optional(lazy(() => data8Schema))],
});
