/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Data5, data5Schema } from './data5';

export interface WalletTransactionsResponse {
  data?: Data5;
}

export const walletTransactionsResponseSchema: Schema<WalletTransactionsResponse> = object(
  { data: ['data', optional(lazy(() => data5Schema))] }
);
