/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Data6, data6Schema } from './data6';

export interface WalletNFTsResponse {
  data?: Data6;
}

export const walletNFTsResponseSchema: Schema<WalletNFTsResponse> = object({
  data: ['data', optional(lazy(() => data6Schema))],
});
